### ISSUE TITLE
User32.EnumWindows crashes sometimes

### ISSUE THREAD

**Issue by Dragonixxx** [TheGuardianWolf/ThunderbirdTray#10]
On my platform, the call to `User32.EnumWindows()` crashes sometimes (at least during development).
The debugger fails to execute `User32.GetClassName()`  or `User32.GetWindowText()` and just exits.

I have prepared a fix and will send a pull request shortly.
The offending parameter was the ìnt.MaxValue`  nMaxCount parameter in both cases.

**Comment by TheGuardianWolf** [comment]
Pull accepted, new release will be soon.
