### ISSUE TITLE
Thunderbird's main window not found

### ISSUE THREAD

**Issue by mjpiotr** [TheGuardianWolf/ThunderbirdTray#12]
For some non-English locales ThunderbirdTray logs error "Cannot find Thunderbird's main window" and thus does not work. The reason is that, eg. with Polish locale the main window title ends with "– Mozilla Thunderbird" not with "- Mozilla Thunderbird" as in English (US/GB).
#### pl
![pl](https://user-images.githubusercontent.com/61086816/74590186-10b53f80-4fda-11ea-8bd2-d5a8ae0db345.jpg)
#### en-GB
![en-GB](https://user-images.githubusercontent.com/61086816/74590166-e4012800-4fd9-11ea-8619-ddd4cca1634f.jpg)

**Comment by TheGuardianWolf** [comment]
Nice find, I knew something might come up after #5 , I didn't expect the dash though.

**Comment by TheGuardianWolf** [comment]
Should be fixed in 1.3.4, let me know if not.
