### ISSUE TITLE
Huge tray allert if email subject is too long

### ISSUE THREAD

**Issue by vvld** [TheGuardianWolf/ThunderbirdTray#15]
Hi,

Thanks for the app, it works great but when a message is received and the new message alert pops up in the tray corner, if the message subject is long then the pop up extends to fit the entire subject text which could be huge. 
It would have been great to work like the other addons which limited the characters for the subject line in the popup alert. Probably somewhere around 30 characters.
I'm using Thunderbird x64 v 68.5.0 on win 7 with ThunderbirdTray NETframework v1.3.4. I use this version instead of 1.4.0 because I want it maximized on start. Could this be also added like an option in the future version or can you please tell me how to change this behavior myself?

Thank you.

**Comment by TheGuardianWolf** [comment]
I'm not sure what you mean about the pop up text, my app only provides a tray icon. Thunderbird has a new message popup as part of its own set of features, is that what you mean? You can test it if you don't run the app and just message yourself.

For the startup option, I'll try to make a way to configure this for next release.

**Comment by TheGuardianWolf** [comment]
This has been added in the latest release

**Comment by vvld** [comment]
Hi,

THANK YOU! It works very well.

Also, you are right regarding the pop up text (is the basic function of Thunderbird that has been changed since version 68 by removing the limit from the subject line, which is a very bad decision).

Thanks again. Have a great day!
