### ISSUE TITLE
Updater is crashing when running it again

### ISSUE THREAD

**Issue by Kacper1263** [TheGuardianWolf/ThunderbirdTray#20]
Hi. 
Your updater is crashing after second (third etc.) run. 

First run was successful and EXE was installed but when I run it again its crashing.

Error log:
```
Starting ThunderbirdTray updater (v1.0.1), CTRL-C to abort.
Detecting current release...
Installation directory C:\Users\Kacper\Downloads\ThunderbirdTray will be cleaned on update.
Detected current version as v1.6.0.
Checking for latest release...
Newest release is v1.6.0.
Traceback (most recent call last):
  File "updater.py", line 234, in <module>
  File "updater.py", line 141, in main
  File "updater.py", line 68, in compare_versions
TypeError: '<' not supported between instances of 'int' and 'str'
[15476] Failed to execute script updater
```

Regards

**Comment by Kacper1263** [comment]
I sent a fix that fixes it. #21

**Comment by TheGuardianWolf** [comment]
Thanks for finding the issue, I've patched it myself fixing the line I messed up on before that function runs.

I'll be looking to integrate the updater into the main application at some point, it looks like it's providing useful functionality.

https://github.com/TheGuardianWolf/ThunderbirdTray/commit/2000d2b4a2135d08c35f495902b2ccb2aa50b98d
