### ISSUE TITLE
Bring other ThunderbirdTray instances up front when ran

### ISSUE THREAD

**Issue by snake-4** [TheGuardianWolf/ThunderbirdTray#22]
It would be nice if there was an option to bring other ThunderbirdTray instances up front when the program is ran instead of saying "Instance already running". Because I would like to replace the Thunderbird shortcut in my taskbar with a shortcut to this program.

**Comment by TheGuardianWolf** [comment]
Seems reasonable, I'll make this change when I next work on it.

**Comment by TheGuardianWolf** [comment]
Finally did this in 1.7.1
