### ISSUE TITLE
Could you give a bit of a non-technical explanation of how to use it?

### ISSUE THREAD

**Issue by fountainofdata** [TheGuardianWolf/ThunderbirdTray#27]
Hi, I would like to use this but I could not find an exe file in the zip. Could you give some extra guidance as to how to use this? I don't have much technical knowledge using the Windows shell.
Thanks in advance!

**Comment by danielb7390** [comment]
Did you donwload the zip from the releases page? Both zips provided there have a executable file. It actually has a thunderbird icon as well.
Just installed this and it's working fine

**Comment by TheGuardianWolf** [comment]
I don't know why GitHub changed the UI so releases are no longer at the top

What you're looking for is the second download on the list here https://github.com/TheGuardianWolf/ThunderbirdTray/releases/tag/v1.7.1
