### ISSUE TITLE
Exe file

### ISSUE THREAD

**Issue by vincentdemers** [TheGuardianWolf/ThunderbirdTray#3]
Hello, 

I'm interested in using your code. In your instructions you indicate that I should place a shortcut to the .exe file but I cannot find any .exe file in this repository. I am missing something?

Thanks Vincent

**Comment by TheGuardianWolf** [comment]
Hey, the releases are here: https://github.com/TheGuardianWolf/ThunderbirdTray/releases

I've put better instructions down on the README as well, I think that should help people pick which version to use.
