### ISSUE TITLE
Tray unread count

### ISSUE THREAD

**Issue by SergioBarbery** [TheGuardianWolf/ThunderbirdTray#9]
Is there any ability/plans to add unread message count to Tray Icon?

**Comment by TheGuardianWolf** [comment]
There is an addon available for Thunderbird that does this independently:

https://addons.thunderbird.net/en-US/thunderbird/addon/unread-badge/

Also, there is an alternative application that can do this I think, does this application suit your needs? It is a lot more advanced than my implementation and I have not tried it out myself.

https://github.com/gyunaev/birdtray

In regards to this application, Thunderbird shows its own unread message icon when there are messages, I would rather not try to hide that one and show my own. 

I would also have to develop an extension for Thunderbird or read the email database directly, which adds complexity.

**Comment by SergeyMaltsev** [comment]
Hi!

Thank you for the reply!
I'll try suggested addon/app.

**Comment by SergioBarbery** [comment]
Hi!
Great! Will try them both!
Thanks!

**Comment by TheGuardianWolf** [comment]
Hopefully this has been resolved, closing issue. Reopen if needed.
